### ISSUE TITLE
Issue with displaying the transaction amount when sending a transaction via multisig

### ISSUE THREAD

**Issue by indigonico** [TronLink/tronlink-android-core#5]
When one of the signers receives a notification and wants to sign the transaction, the amount is not displayed in the signing request.

Phone model is shown in the screenshot. App: TRONLINK PRO

This bug occurred on November 12, 2024. Is there a way to fix it or avoid encountering it?

Device info: Huawei NOVA 12i

![telegram-cloud-photo-size-2-5303170887341698417-y](https://github.com/user-attachments/assets/cb0c3788-28a1-4180-bfac-702efe716b9d)

on the screenshot I highlighted the place where the amount of funds (USDT) was displayed before this bug. 

E.g. how it should look like from official tronlink doc https://arc.net/l/quote/osiiiixs
it worked that way before

**Comment by tronlinkdev** [comment]
Thanks for the feedback, the issue has been fixed now.

**Comment by indigonico** [comment]
Appreciated for the rapid response and fix!

Thanks! Going to do the same issue for the iOS app😂
